# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('date_assigned', models.CharField(max_length=12)),
                ('due_date', models.CharField(max_length=12)),
                ('priority_level', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
