# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.Job')),
            ],
        ),
    ]
