# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='name',
        ),
        migrations.AddField(
            model_name='goal',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
