# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_auto_20161129_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
