# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20161129_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
